server:
  port: 2704

spring:
  application:
    name: user-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/edunova_user
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: 3600

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true