server:
  port: 2704

spring:
  application:
    name: user-service
  
  datasource:
    url: jdbc:postgresql://192.168.1.199:5432/edunova
    username: postgres
    password: secret

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: 3600
management:
  endpoints:
    web:
      exposure:
        include: "health"
eureka:
  instance:
    health-check-url-path: /actuator/health
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/