server:
  port: 8888
spring:
  application:
    name: edunova-configuration-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:../configurations

logging:
  level:
    org.springframework.cloud.config: DEBUG
