server:
  port: 2703

spring:
  application:
    name: edunova-configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/merendemir/edunova.git
          default-label: master
          search-paths: configurations/
encrypt:
  key: edunova-encryptsecret-key-123
