server:
  port: 2703
spring:
  application:
    name: edunova-configuration-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:../configurations
encrypt:
  key: edunova-encryptsecret-key-123

logging:
  level:
    org.springframework.cloud.config: DEBUG
